ed_lora_dir: "artifacts/ed_lora"
base_model:
  use: "dreamshaper_8"
  ds8: "/srv/models/dreamshaper_8.safetensors"
  dreamshaper_8: "/srv/models/external/dreamshaper_8.safetensors"
  sd15: "/srv/models/v1-5-pruned-emaonly.safetensors"
trigger_token: "svtchar"
local_docker: true
train:
  resolution: 512
  steps: 2500
  network_dim: 32
  unet_only: true
  save_every: 500
  mixed_precision: fp16
kohya:
  accelerate_bin: "accelerate"
  script_path: "${KOHYA_ROOT}/train_network.py"
  workspace: "${KOHYA_ROOT}"
  output_subdir: "output"
  network_module: "networks.lora"


